redirects:
  click-here-for-help/troubleshooting-errors: welcome-to-pancakeswap/contact-us/faq/troubleshooting
  click-here-for-help/README: welcome-to-pancakeswap/contact-us/faq/help
  click-here-for-help/faq: welcome-to-pancakeswap/contact-us/faq/README
  click-here-for-help/ru-he-xiu-fu-metamask-shang-ka-zhu-de-jiao-yi: welcome-to-pancakeswap/contact-us/faq/unsticking-a-transaction-stuck-as-pending-with-metamask
  contact-us/customer-support: welcome-to-pancakeswap/contact-us/faq/help
